### ISSUE TITLE
automatically generate js test file for sb3 file

### ISSUE THREAD

**Issue by Annrison** [marvinkreis/whisker-web#8]
hello, recently I'm studying the paper "Testing Scratch Programs Automatically",
I wonder if there is a way to generate js file to test students' sb3 files automatically ?
Or we have to write every js file for each test by our selves?

Thanks for reading.

**Comment by stahlbauer** [comment]
Hi. The test cases (test inputs and property to satisfy) has to be provided by the user. Are you looking for an approach to infere (generate) the specification (sets of properties to satisfy) automatically? Or a test generator for Scratch programs?

**Comment by Annrison** [comment]
thanks for your quick reply,
I would like to ask about the way to generate specification automatically,
like the file in the repository artifact-esecfse2019  which path is "data/test-seeded/test-random.js".

And if the properties have to be provided by the user, 
is there a guide document to follow expect for the README.md in software file?

**Comment by marvinkreis** [comment]
Hi. The tests you're referring to (test-random.js) were manually written. The random part of them comes from Whisker generating random inputs for the program to test the given constraints. However, a way to infer constraints through search-based testing is currently being worked on (but I can't tell you more about it, since I'm not involved with it).

We don't provide much documentation at this point, as there a still some things that need ironing out. I can only point you to the [implementation of the testing API](https://github.com/se2p/whisker-main/blob/master/src/test/test-driver.js), which has links to all the methods that can be called in tests, and [chapter 3-5 of the thesis that started Whisker](https://github.com/marvinkreis/bachelor-thesis/blob/master/thesis.pdf). Of course, if you have questions about anything, you can always ask us.

**Comment by gofraser** [comment]
We are working on automatically generating js files as well; see https://arxiv.org/abs/2009.04115 for a report on the general idea. An initial version will hopefully be included in the next release of Whisker, but this only covers the part of generating *inputs* to the program, inferring constraints is planned but will take longer.

**Comment by Annrison** [comment]
Thanks you so much!!!  I'll check the paper definitely. 
But currently I have some question about testing sprite's position, could I open a new issue?

**Comment by gofraser** [comment]
Yes, if the question is independent of this issue then a new issue sounds like a good idea.
